// <auto-generated />
using System;
using GameServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations.GameDb
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedLibrary.Models.ObjectLifecycleLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("ClaimedTime")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "claimedTime");

                    b.Property<DateTime?>("ClientSpawnedTime")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "clientSpawnedTime");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("ServerSpawnedTime")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "serverSpawnedTime");

                    b.HasKey("LogId");

                    b.ToTable("ObjectLifecycleLogs");
                });

            modelBuilder.Entity("SharedLibrary.Models.PlayerSessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttemptedClientScore")
                        .HasColumnType("int");

                    b.Property<int?>("BlockedSpawns")
                        .HasColumnType("int");

                    b.Property<int?>("ClientObjCount")
                        .HasColumnType("int");

                    b.Property<float?>("CurrentSpawnRadius")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesyncResolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FakeObjectDetected")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlaggedForReview")
                        .HasColumnType("bit");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HashMismatch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSpawnAttempt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObjectLifecycleLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectSyncHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PickupEventsVerified")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RadiusEnforced")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreServer")
                        .HasColumnType("int");

                    b.Property<int?>("ServerObjCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionMetadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SpawnRateFlagged")
                        .HasColumnType("bit");

                    b.Property<int?>("SpawnRequests")
                        .HasColumnType("int");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValidatedSpawns")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessionLog", "gameplay");
                });

            modelBuilder.Entity("SharedLibrary.Models.RefreshTokenRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokenRecord", "auth");
                });

            modelBuilder.Entity("SharedLibrary.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("SharedLibrary.Models.ObjectLifecycleLog", b =>
                {
                    b.OwnsOne("SharedLibrary.Common.Position", "Coordinates", b1 =>
                        {
                            b1.Property<int>("ObjectLifecycleLogLogId")
                                .HasColumnType("int");

                            b1.Property<float>("X")
                                .HasColumnType("real")
                                .HasAnnotation("Relational:JsonPropertyName", "X");

                            b1.Property<float>("Y")
                                .HasColumnType("real")
                                .HasAnnotation("Relational:JsonPropertyName", "Y");

                            b1.HasKey("ObjectLifecycleLogLogId");

                            b1.ToTable("ObjectLifecycleLogs");

                            b1.HasAnnotation("Relational:JsonPropertyName", "coordinates");

                            b1.WithOwner()
                                .HasForeignKey("ObjectLifecycleLogLogId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("SharedLibrary.Models.PlayerSessionLog", b =>
                {
                    b.OwnsOne("SharedLibrary.Common.Position", "LastKnownPosition", b1 =>
                        {
                            b1.Property<int>("PlayerSessionLogId")
                                .HasColumnType("int");

                            b1.Property<float>("X")
                                .HasColumnType("real")
                                .HasAnnotation("Relational:JsonPropertyName", "X");

                            b1.Property<float>("Y")
                                .HasColumnType("real")
                                .HasAnnotation("Relational:JsonPropertyName", "Y");

                            b1.HasKey("PlayerSessionLogId");

                            b1.ToTable("PlayerSessionLog", "gameplay");

                            b1.WithOwner()
                                .HasForeignKey("PlayerSessionLogId");
                        });

                    b.Navigation("LastKnownPosition");
                });
#pragma warning restore 612, 618
        }
    }
}
